<?php 
// Each 'setId' below is locked so all completed/previous shape stems keep same expected set of shapes.
// Thus, new shapes must never be added to old setIds.
// Generally, a new setId should be established for each new 'batch' of related stems, requiring those shapes.

return [
    [   
        'id' => 1,
        'setId' => 1,
        'name' => 'isosceles triangle',
        'pathData' => ['shape' => ['M40,150 L90,30 L140,150 z'], 'lineSymmetry' => ['M90,0 V180'], 'lineAsymmetry' => ['M0,90 H180']],
        'linesOfSymmetry' => 1,
        'acuteAngles' => 3,
        'gridFriendly' => true,
        'type' => ['triangle', 'irregular polygon'],
        'subType' => ['acute', 'isosceles', 'oblique'],
        'sides' => 3,
    ], [
        'id' => 2,
        'setId' => 1,
        'name' => 'diamond (vertical)',
        'pathData' => ['shape' => ['M30,90 L90,10 L150,90 L90,170 z'], 'lineSymmetry' => ['M90,0 V180', 'M0,90 H180'], 'lineAsymmetry' => ['M20,0 L160,180']],
        'linesOfSymmetry' => 2,
        'parallelSets' => 2,
        'obtuseAngles' => 2,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['rhombus', 'parallelogram', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'sides' => 4,
    ], [
        'id' => 3,
        'setId' => 1,
        'name' => 'arrow sign (square edges)',
        'pathData' => ['shape' => ['M30,10 L90,10 L150,90 L90,170 L30,170 L90,90 z'], 'lineSymmetry' => ['M0,90 H180'], 'lineAsymmetry' => ['M90,0 V180']],
        'linesOfSymmetry' => 1,
        'parallelSets' => 3,
        'obtuseAngles' => 3,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['irregular hexagon', 'concave hexagon', 'irregular polygon'],
        'subType' => ['concave'],
        'sides' => 6,
    ], [
        'id' => 4,  
        'setId' => 1,
        'name' => 'trapezoid (tall, wide)',
        'pathData' => ['shape' => ['M10,150 L40,30 L140,30 L170,150 z'], 'lineSymmetry' => ['M90,0 V180'], 'lineAsymmetry' => ['M0,90 H180']],
        'linesOfSymmetry' => 1,
        'parallelSets' => 1,
        'obtuseAngles' => 2,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['trapezoid', 'acute trapezoid', 'isosceles trapezoid', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'subType' => ['acute','isosceles'],
        'sides' => 4,
    ], [
        'id' => 5,  
        'setId' => 1,
        'name' => 'irregular pentagon',
        'pathData' => ['shape' => ['M10,50 L130,50 L170,90 L130,130 L10,130 z'], 'lineSymmetry' => ['M0,90 H180'], 'lineAsymmetry' => ['M90,0 V180']],
        'linesOfSymmetry' => 1,
        'parallelSets' => 1,
        'perpendicularSets' => 3,
        'rightAngles' => 3,
        'obtuseAngles' => 2,
        'gridFriendly' => true,
        'type' => ['irregular pentagon', 'irregular polygon'],
        'sides' => 5,
    ], [
        'id' => 6,  
        'setId' => 1,
        'name' => 'hexagon',
        'pathData' => ['shape' => ['M10,90 L50,20 L130,20 L170,90 L130,160 L50,160 z'], 'lineSymmetry' => ['M90,0 V180', 'M0,90 H180', 'M0,40 L180,140']],
        'linesOfSymmetry' => 6,
        'parallelSets' => 3,
        'obtuseAngles' => 6,
        'gridFriendly' => true,
        'type' => ['hexagon', 'polygon', 'regular polygon'],
        'sides' => 6,
    ], [
        'id' => 7,  
        'setId' => 1,
        'name' => 'square (tall)',
        'pathData' => ['shape' => ['M20,20 L160,20 L160,160 L20,160 z'], 'lineSymmetry' => ['M0,90 H180', 'M180,0 L0,180']],
        'linesOfSymmetry' => 4,
        'parallelSets' => 2,
        'perpendicularSets' => 4,
        'rightAngles' => 4,
        'gridFriendly' => true,
        'type' => ['square', 'rectangle', 'rhombus', 'parallelogram', 'quadrilateral', 'regular quadrilateral', 'polygon', 'regular polygon'],
        'sides' => 4,
    ], [
        'id' => 8,  
        'setId' => 1,
        'name' => 'right triangle (tall, thin)',
        'pathData' => ['shape' => ['M60,20 L120,160 L60,160 z']],
        'perpendicularSets' => 1,
        'rightAngles' => 1,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['triangle', 'irregular polygon'],
        'subType' => ['right', 'scalene'],
        'sides' => 3,
    ], [
        'id' => 9,  
        'setId' => 1,
        'name' => 'irregular heptagon (arrow, square base)',
        'pathData' => ['shape' => ['M20,70 L120,70 L120,50 L160,90 L120,130 L120,110 L20,110 z'], 'lineSymmetry' => ['M0,90 H180'], 'lineAsymmetry' => ['M90,0 V180']],
        'linesOfSymmetry' => 1,
        'parallelSets' => 3,
        'perpendicularSets' => 3,
        'rightAngles' => 3,
        'acuteAngles' => 2,
        'type' => ['irregular heptagon', 'irregular polygon'],
        'subType' => ['concave'],
        'sides' => 7,
    ], [
        'id' => 10,  
        'setId' => 1,
        'name' => 'irregular octagon (arrow, winged base)',
        'pathData' => ['shape' => ['M10,70 L130,70 L130,50 L170,90 L130,130 L130,110 L10,110 L30,90 z'], 'lineSymmetry' => ['M0,90 H180'], 'lineAsymmetry' => ['M90,0 V180']],
        'linesOfSymmetry' => 1,
        'parallelSets' => 3,
        'perpendicularSets' => 1,
        'rightAngles' => 1,
        'acuteAngles' => 4,
        'type' => ['irregular octagon', 'irregular polygon'],
        'subType' => ['concave'],
        'sides' => 8,
    ], [
        'id' => 11,  
        'setId' => 1,
        'name' => 'irregular hendecagon (box with arrow)',
        'pathData' => ['shape' => ['M15,40 L115,40 L115,77.5 L140,77.5 L140,65 L165,90 L140,115 L140,102.5 L115,102.5 L115,140 L15,140 z'], 'lineSymmetry' => ['M0,90 H180'], 'lineAsymmetry' => ['M60,0 V180']],
        'linesOfSymmetry' => 1,
        'parallelSets' => 14,
        'perpendicularSets' => 5,
        'rightAngles' => 5,
        'acuteAngles' => 2,
        'type' => ['irregular hendecagon', 'irregular polygon'],
        'subType' => ['concave'],
        'sides' => 11,
    ], [
        'id' => 12,  
        'setId' => 1,
        'name' => 'pentagon',
        'pathData' => ['shape' => ['M90,14.375 L10.48,72.145 L40.85,165.625 L139.14,165.625 L169.52,72.145 z'], 'lineSymmetry' => ['M90,0 V180'], 'lineAsymmetry' => ['M0,90 H180']],
        'linesOfSymmetry' => 5,
        'obtuseAngles' => 5,
        'type' => ['pentagon', 'polygon', 'regular polygon'],
        'sides' => 5,
    ], [
        'id' => 13,  
        'setId' => 1,
        'name' => 'heptagon',
        'pathData' => ['shape' => ['M90,12.555 L153.29,43.225 L168.92,112.155 L125.12,167.445 H54.88 L11.08,112.155 L26.71,43.225 z'], 'lineSymmetry' => ['M90,0 V180'], 'lineAsymmetry' => ['M0,90 H180']],
        'linesOfSymmetry' => 7,
        'obtuseAngles' => 7,
        'type' => ['heptagon', 'polygon', 'regular polygon'],
        'sides' => 7,
    ], [
        'id' => 14,  
        'setId' => 1,
        'name' => 'street sign',
        'pathData' => ['shape' => ['M10,40 A30,30 0,0 0 40,10 L140,10 A30,30 0,0 0 170,40 L170,140 A30,30 0,0 0 140,170 L40,170 A30,30 0,0 0 10,140 z'], 'lineSymmetry' => ['M0,90 H180', 'M0,0 L180,180']],
        'linesOfSymmetry' => 4,
        'parallelSets' => 2,
        'type' => ['closed curve'],
        'subType' => ['simple'],
    ], [
        'id' => 15,
        'setId' => 2,
        'name' => 'right trapezoid (short, wide)',
        'pathData' => ['shape' => ['M20,60 L100,60 L160,120 L20,120 z']],
        'parallelSets' => 1, 
        'perpendicularSets' => 2,
        'rightAngles' => 2,
        'obtuseAngles' => 1,
        'acuteAngles' => 1,
        'gridFriendly' => true,
        'type' => ['trapezoid', 'right trapezoid', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'subType' => ['right'],
        'sides' => 4,
    ], [
        'id' => 16,
        'setId' => 2,
        'name' => 'right trapezoid (wide)',
        'pathData' => ['shape' => ['M20,40 L80,40 L160,140 L20,140 z']],
        'parallelSets' => 1, 
        'perpendicularSets' => 2,
        'rightAngles' => 2,
        'obtuseAngles' => 1,
        'acuteAngles' => 1,
        'gridFriendly' => true,
        'type' => ['trapezoid', 'right trapezoid', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'subType' => ['right'],
        'sides' => 4,
    ], [
        'id' => 17,
        'setId' => 2,
        'name' => 'right trapezoid',
        'pathData' => ['shape' => ['M40,40 L80,40 L140,140 L40,140 z']],
        'parallelSets' => 1, 
        'perpendicularSets' => 2,
        'rightAngles' => 2,
        'obtuseAngles' => 1,
        'acuteAngles' => 1,
        'gridFriendly' => true,
        'type' => ['trapezoid', 'right trapezoid', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'subType' => ['right'],
        'sides' => 4,
    ], [
        'id' => 18,
        'setId' => 2,
        'name' => 'rectangle (tall, thin)',
        'pathData' => ['shape' => ['M60,20 L120,20 L120,160 L60,160 z']],
        'parallelSets' => 2, 
        'perpendicularSets' => 4,
        'rightAngles' => 4,
        'gridFriendly' => true,
        'type' => ['rectangle', 'parallelogram', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'sides' => 4,
    ], [
        'id' => 19,
        'setId' => 2,
        'name' => 'rectangle (tall, wide)',
        'pathData' => ['shape' => ['M40,20 L140,20 L140,160 L40,160 z']],
        'parallelSets' => 2, 
        'perpendicularSets' => 4,
        'rightAngles' => 4,
        'gridFriendly' => true,
        'type' => ['rectangle', 'parallelogram', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'sides' => 4,
    ], [
        'id' => 20,
        'setId' => 2,
        'name' => 'rectangle (short, thin)',
        'pathData' => ['shape' => ['M60,40 L120,40 L120,140 L60,140 z']],
        'parallelSets' => 2,
        'perpendicularSets' => 4,
        'rightAngles' => 4,
        'gridFriendly' => true,
        'type' => ['rectangle', 'parallelogram', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'sides' => 4,
    ], [
        'id' => 21,
        'setId' => 2,
        'name' => 'trapezium',
        'pathData' => ['shape' => ['M20,40 L120,40 L160,100 L20,140 z']],
        'perpendicularSets' => 1,
        'rightAngles' => 1,
        'obtuseAngles' => 1,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['trapezium', 'irregular quadrilateral', 'irregular polygon'],
        'subType' => ['right'],
        'sides' => 4,
    ], [
        'id' => 22,
        'setId' => 2,
        'name' => 'trapezium (short)',
        'pathData' => ['shape' => ['M20,60 L120,60 L160,100 L20,120 z']],
        'perpendicularSets' => 1,
        'rightAngles' => 1,
        'obtuseAngles' => 1,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['trapezium', 'irregular quadrilateral', 'irregular polygon'],
        'subType' => ['right'],
        'sides' => 4,
    ], [
        'id' => 23,
        'setId' => 2,
        'name' => 'concave quadrilateral (dart)',
        'pathData' => ['shape' => ['M20,160 L120,140 L160,20 L160,160 z']],
        'perpendicularSets' => 1,
        'rightAngles' => 1,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['trapezium', 'dart', 'concave quadrilateral', 'irregular quadrilateral', 'irregular polygon'],
        'subType' => ['concave'],
        'sides' => 4,
    ], [
        'id' => 24,
        'setId' => 3,
        'name' => 'right triangle (wide)',
        'pathData' => ['shape' => ['M20,40 L160,140 L20,140 z']],
        'perpendicularSets' => 1,
        'rightAngles' => 1,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['triangle', 'right triangle', 'scalene triangle', 'irregular polygon'],
        'subType' => ['right', 'scalene'],
        'sides' => 3,
    ], [
        'id' => 25,
        'setId' => 3,
        'name' => 'right triangle (tall, wide)',
        'pathData' => ['shape' => ['M20,20 L160,160 L20,160 z']],
        'perpendicularSets' => 1,
        'rightAngles' => 1,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['triangle', 'right triangle', 'isosceles triangle', 'irregular polygon'],
        'subType' => ['right', 'isosceles'],
        'sides' => 3,
    ], [
        'id' => 26,
        'setId' => 3,
        'name' => 'right triangle',
        'pathData' => ['shape' => ['M40,40 L140,140 L40,140 z']],
        'perpendicularSets' => 1,
        'rightAngles' => 1,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['triangle', 'right triangle', 'isosceles triangle', 'irregular polygon'],
        'subType' => ['right', 'isosceles'],
        'sides' => 3,
    ], [
        'id' => 27,
        'setId' => 3,
        'name' => 'right triangle (very thin)',
        'pathData' => ['shape' => ['M75,40 L105,140 L75,140 z']],
        'perpendicularSets' => 1,
        'rightAngles' => 1,
        'acuteAngles' => 2,
        'type' => ['triangle', 'right triangle', 'scalene triangle', 'irregular polygon'],
        'subType' => ['right', 'scalene'],
        'sides' => 3,
    ], [
        'id' => 28,
        'setId' => 3,
        'name' => 'right triangle (tall, very thin)',
        'pathData' => ['shape' => ['M75,20 L105,160 L75,160 z']],
        'perpendicularSets' => 1,
        'rightAngles' => 1,
        'acuteAngles' => 2,
        'type' => ['triangle', 'right triangle', 'scalene triangle', 'irregular polygon'],
        'subType' => ['right', 'scalene'],
        'sides' => 3,
    ], [
        'id' => 29,
        'setId' => 3,
        'name' => 'equilateral triangle (tall)',
        'pathData' => ['shape' => ['M90,20.14 L9.01,159.86 L170.99,159.86 z']],
        'acuteAngles' => 3,
        'type' => ['triangle', 'equilateral triangle', 'polygon', 'regular polygon'],
        'subType' => ['acute', 'equilateral'],
        'sides' => 3,
    ], [
        'id' => 30,
        'setId' => 3,
        'name' => 'equilateral triangle',
        'pathData' => ['shape' => ['M90.005,30.14 L20.605,149.86 L159.395,149.86 z']],
        'acuteAngles' => 3,
        'type' => ['triangle', 'equilateral triangle', 'polygon', 'regular polygon'],
        'subType' => ['acute', 'equilateral'],
        'sides' => 3,
    ], [
        'id' => 31,
        'setId' => 3,
        'name' => 'equilateral triangle (short)',
        'pathData' => ['shape' => ['M90,40.21 L32.28,139.79 L147.72,139.79 z']],
        'acuteAngles' => 3,
        'type' => ['triangle', 'equilateral triangle', 'polygon', 'regular polygon'],
        'subType' => ['acute', 'equilateral'],
        'sides' => 3,
    ], [
        'id' => 32,
        'setId' => 3,
        'name' => 'isosceles triangle (tall)',
        'pathData' => ['shape' => ['M30,170 L90,10 L150,170 z']],
        'acuteAngles' => 3,
        'gridFriendly' => true,
        'type' => ['triangle', 'acute triangle', 'isosceles triangle', 'irregular polygon'],
        'subType' => ['acute', 'isosceles'],
        'sides' => 3,
    ], [
        'id' => 33,
        'setId' => 3,
        'name' => 'isosceles triangle (short)',
        'pathData' => ['shape' => ['M50,140 L90,40 L130,140 z']],
        'acuteAngles' => 3,
        'gridFriendly' => true,
        'type' => ['triangle', 'acute triangle', 'isosceles triangle', 'irregular polygon'],
        'subType' => ['acute', 'isosceles'],
        'sides' => 3,
    ], [
        'id' => 34,
        'setId' => 3,
        'name' => 'obtuse triangle (short)',
        'pathData' => ['shape' => ['M20,60 L160,120 L80,120 z']],
        'obtuseAngles' => 1,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['triangle', 'obtuse triangle', 'scalene triangle', 'irregular polygon'],
        'subType' => ['obtuse', 'scalene'],
        'sides' => 3,
    ], [
        'id' => 35,
        'setId' => 3,
        'name' => 'obtuse triangle (tall, thin)',
        'pathData' => ['shape' => ['M40,20 L140,160 L80,160 z']],
        'obtuseAngles' => 1,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['triangle', 'obtuse triangle', 'scalene triangle', 'irregular polygon'],
        'subType' => ['obtuse', 'scalene'],
        'sides' => 3,
    ], [
        'id' => 36,
        'setId' => 3,
        'name' => 'obtuse triangle',
        'pathData' => ['shape' => ['M40,40 L140,140 L60,140 z']],
        'obtuseAngles' => 1,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['triangle', 'obtuse triangle', 'scalene triangle', 'irregular polygon'],
        'subType' => ['obtuse', 'scalene'],
        'sides' => 3,
    ], [
        'id' => 37,
        'setId' => 3,
        'name' => 'obtuse triangle (tall, wide)',
        'pathData' => ['shape' => ['M20,20 L160,160 L60,160 z']],
        'obtuseAngles' => 1,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['triangle', 'obtuse triangle', 'scalene triangle', 'irregular polygon'],
        'subType' => ['obtuse', 'scalene'],
        'sides' => 3,
    ], [
        'id' => 38,
        'setId' => 3,
        'name' => 'obtuse triangle (tall, very thin)',
        'pathData' => ['shape' => ['M20,40 L160,140 L120,140 z']],
        'obtuseAngles' => 1,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['triangle', 'obtuse triangle', 'scalene triangle', 'irregular polygon'],
        'subType' => ['obtuse', 'scalene'],
        'sides' => 3,
    ], [
        'id' => 39,
        'setId' => 3,
        'name' => 'obtuse triangle (thin)',
        'pathData' => ['shape' => ['M40,40 L140,140 L80,140 z']],
        'obtuseAngles' => 1,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['triangle', 'obtuse triangle', 'scalene triangle', 'irregular polygon'],
        'subType' => ['obtuse', 'scalene'],
        'sides' => 3,
    ], [
        'id' => 40,
        'setId' => 4,
        'name' => 'rhombus (short)',
        'pathData' => ['shape' => ['M30.98,124.075 L70.32,55.925 L149.02,55.925 L109.67,124.075 z']],
        'parallelSets' => 2,
        'obtuseAngles' => 2,
        'acuteAngles' => 2,
        'type' => ['rhombus', 'parallelogram', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'sides' => 4,
    ], [
        'id' => 41,
        'setId' => 4,
        'name' => 'rhombus',
        'pathData' => ['shape' => ['M10.965,135.63 L63.645,44.37 L169.035,44.37 L116.345,135.63 z']],
        'parallelSets' => 2,
        'obtuseAngles' => 2,
        'acuteAngles' => 2,
        'type' => ['rhombus', 'parallelogram', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'sides' => 4,
    ], [
        'id' => 42,
        'setId' => 4,
        'name' => 'parallelogram (20 degree tilt)',
        'pathData' => ['shape' => ['M40,50 L170,50 L140,130 L10,130 z']],
        'parallelSets' => 2,
        'obtuseAngles' => 2,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['parallelogram', 'rhomboid', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'sides' => 4,
    ], [
        'id' => 43,
        'setId' => 4,
        'name' => 'parallelogram (35 degree tilt)',
        'pathData' => ['shape' => ['M50,60 L170,60 L130,120 L10,120 z']],
        'parallelSets' => 2,
        'obtuseAngles' => 2,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['parallelogram', 'rhomboid', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'sides' => 4,
    ], [
        'id' => 44,
        'setId' => 4,
        'name' => 'parallelogram (45 degree tilt)',
        'pathData' => ['shape' => ['M70,60 L170,60 L110,120 L10,120 z']],
        'parallelSets' => 2,
        'obtuseAngles' => 2,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['parallelogram', 'rhomboid', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'sides' => 4,
    ], [
        'id' => 45,
        'setId' => 4,
        'name' => 'trapezoid',
        'pathData' => ['shape' => ['M10,130 L40,50 L140,50 L170,130 z']],
        'parallelSets' => 1,
        'obtuseAngles' => 2,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['trapezoid', 'acute trapezoid', 'isosceles trapezoid', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'subType' => ['acute', 'isosceles'],
        'sides' => 4,
    ], [
        'id' => 46,
        'setId' => 4,
        'name' => 'trapezoid (short)',
        'pathData' => ['shape' => ['M30,120 L60,60 L120,60 L150,120 z']],
        'parallelSets' => 1,
        'obtuseAngles' => 2,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['trapezoid', 'acute trapezoid', 'isosceles trapezoid', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'subType' => ['acute', 'isosceles'],
        'sides' => 4,
    ], [
        'id' => 47,
        'setId' => 4,
        'name' => 'right trapezoid (tall)',
        'pathData' => ['shape' => ['M50,10 L110,10 L130,170 L50,170 z']],
        'parallelSets' => 1, 
        'perpendicularSets' => 2,
        'rightAngles' => 2,
        'obtuseAngles' => 1,
        'acuteAngles' => 1,
        'gridFriendly' => true,
        'type' => ['trapezoid', 'right trapezoid', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'subType' => ['right'],
        'sides' => 4,
    ], [
        'id' => 48,
        'setId' => 4,
        'name' => 'concave quadrilateral (10 degree base tilt)',
        'pathData' => ['shape' => ['M30,140 L70,130 L110,20 L150,160 z']],
        'acuteAngles' => 3,
        'gridFriendly' => true,
        'type' => ['trapezium', 'concave quadrilateral', 'irregular quadrilateral', 'irregular polygon'],
        'subType' => ['concave'],
        'sides' => 4,
    ], [
        'id' => 49,
        'setId' => 4,
        'name' => 'concave quadrilateral (arrowhead)',
        'pathData' => ['shape' => ['M20,160 L90,20 L160,160 L90,100 z']],
        'acuteAngles' => 3,
        'gridFriendly' => true,
        'type' => ['trapezium', 'concave quadrilateral', 'irregular quadrilateral', 'irregular polygon'],
        'subType' => ['concave'],
        'sides' => 4,
    ], [
        'id' => 50,
        'setId' => 4,
        'name' => 'crossed quadrilateral (hourglass)',
        'pathData' => ['shape' => ['M60,50 L120,30 L60,130 L120,150 z']],
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['crossed quadrilateral', 'complex quadrilateral', 'irregular quadrilateral', 'irregular polygon'],
        'subType' => ['crossed'],
        'sides' => 4,
    ], [
        'id' => 51,
        'setId' => 4,
        'name' => 'irregular quadrilateral (star destroyer)',
        'pathData' => ['shape' => ['M40,120 L50,40 L140,90 L100,140 z']],
        'obtuseAngles' => 2,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['irregular quadrilateral', 'irregular polygon'],
        'sides' => 4,
    ], [
        'id' => 52,
        'setId' => 4,
        'name' => 'diamond (horizontal)',
        'pathData' => ['shape' => ['M20,90 L90,40 L160,90 L90,140 z']],
        'parallelSets' => 2,
        'obtuseAngles' => 2,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['rhombus', 'parallelogram', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'sides' => 4,
    ], [
        'id' => 53,
        'setId' => 4,
        'name' => 'rhombus (10 degree base tilt)',
        'pathData' => ['shape' => ['M20,140 L70,50 L170,40 L110,130 z']],
        'parallelSets' => 2,
        'obtuseAngles' => 2,
        'acuteAngles' => 2,
        'gridFriendly' => true,
        'type' => ['rhombus', 'parallelogram', 'quadrilateral', 'regular quadrilateral', 'irregular polygon'],
        'sides' => 4,
    ], [
        'id' => 54,
        'setId' => 4,
        'name' => 'square (45 degree base tilt)',
        'pathData' => ['shape' => ['M10,90 L90,10 L170,90 L90,170 z']],
        'parallelSets' => 2,
        'perpendicularSets' => 4,
        'rightAngles' => 4,
        'gridFriendly' => true,
        'type' => ['square', 'rectangle', 'rhombus', 'parallelogram', 'quadrilateral', 'regular quadrilateral', 'polygon', 'regular polygon'],
        'sides' => 4,
    ], [
        'id' => 55,
        'setId' => 4,
        'name' => 'square',
        'pathData' => ['shape' => ['M40,40 L140,40 L140,140 L40,140 z']],
        'parallelSets' => 2,
        'perpendicularSets' => 4,
        'rightAngles' => 4,
        'gridFriendly' => true,
        'type' => ['square', 'rectangle', 'rhombus', 'parallelogram', 'quadrilateral', 'regular quadrilateral', 'polygon', 'regular polygon'],
        'sides' => 4,
    ], [
        'id' => 56,
        'setId' => 4,
        'name' => 'square (15 degree base tilt)',
        'pathData' => ['shape' => ['M60,40 L140,60 L120,140 L40,120 z']],
        'parallelSets' => 2,
        'perpendicularSets' => 4,
        'rightAngles' => 4,
        'gridFriendly' => true,
        'type' => ['square', 'rectangle', 'rhombus', 'parallelogram', 'quadrilateral', 'regular quadrilateral', 'polygon', 'regular polygon'],
        'sides' => 4,
    ], [
        'id' => 57,
        'setId' => 5,
        'name' => 'cube',
        'pathData' => ['shape' => ['M48.635,131.525 L48.635,10 M48.635,131.525 L10,170 M48.635,131.525 L170,131.525', 'M10,170 L131.36,170 L170,131.525 L170,10 L48.635,10 L10,48.635 L10,170', 'M131.36,48.635 L10,48.635 M131.36,48.635 L170,10 M131.36,48.635 L131.36,170']],
        'parallelSets' => 18,
        'perpendicularSets' => 24,
        'rightAngles' => 24,
        'type' => ['cube', 'square prism'],
        'subType' => ['prism'],
        'sides' => 6,
        'corners' => 8,
        'edges' => 12,
        'faces' => 6,
    ], [
        'id' => 58,
        'setId' => 5,
        'name' => 'rectangular prism',
        'pathData' => ['shape' => ['M40,110 L40,40 M40,110 L10,140 M40,110 L170,110', 'M170,40 L170,110 L140,140 L10,140 L10,70 L40,40 L170,40', 'M10,70 L140,70 L170,40 M140,70 L140,140']],
        'parallelSets' => 18,
        'perpendicularSets' => 24,
        'rightAngles' => 24,
        'gridFriendly' => true,
        'type' => ['rectangular prism'],
        'subType' => ['prism'],
        'sides' => 6,
        'corners' => 8,
        'edges' => 12,
        'faces' => 6,
    ],
];
